version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:rc-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py2-pip curl
            pip install \
              docker-compose \
              awscli
      - run:
          name: Build application Docker image
          command: |
            docker build -t flask-app-development:latest  . 
            docker build -t flask-app-production:latest -f deploy/Dockerfile .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login  --no-include-email --region us-east-1)"
              ${login}
              docker tag flask-app-production "${ECR_URL}:latest"
              docker push "${ECR_URL}:latest"
            fi
      - deploy:
          name: Deploy Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
              chmod +x /usr/local/bin/ecs-cli
              ecs-cli configure --cluster flask-app-cluster --region ap-northeast-1 --default-launch-type EC2 --config-name flask-app-config
              ecs-cli compose --file deploy/docker-compose.yml up --create-log-groups --cluster-config flask-app-config
            fi